### ISSUE TITLE
Features to add to Blast Off

### ISSUE THREAD

**Issue by ronan18** [StompRocket/BlastOff#6]
* [ ] Mobile responsive navbar
* [x] Navbar that keeps links and images horizontally aligned
* [ ] Inputs
* [x] Sass color varibles
* [ ] Style Guide
* [x] Modals
* [ ] Toasts

**Comment by ronan18** [comment]
# Some more stuff:

* [ ] Simple parallax(might be interesting) https://daverupert.com/2018/02/cheapass-parallax/
* [x] Titles that have slightly offset bolded underlines

**Comment by swissChili** [comment]
Pure css toast is possible, but will require JavaScript for the timed close functionality.
